version: '3.8'
services:
  sirpElasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch    
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:      
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch2,elasticsearch3
      - cluster.initial_master_nodes="elasticsearch","elasticsearch2","elasticsearch3"
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
      # - xpack.security.enabled=true
      # - xpack.security.transport.ssl.enabled=true
      # - xpack.security.transport.ssl.keystore.type=PKCS12
      # - xpack.security.transport.ssl.verification_mode=certificate
      # - xpack.security.transport.ssl.keystore.path=elastic-stack-ca.p12
      # - xpack.security.transport.ssl.truststore.path=elastic-stack-ca.p12
      # - xpack.security.transport.ssl.truststore.type=PKCS12     
      # - xpack.security.transport.ssl.keystore.password=123456
      # - xpack.security.transport.ssl.truststore.password=123456


    volumes:
      - volElasticsearchData:/usr/share/elasticsearch/data
      - $PWD/ssl/elastic-stack-ca.p12:/usr/share/elasticsearch/config/elastic-stack-ca.p12
      #- $PWD/volumes/volElasticsearchData:/usr/share/elasticsearch/data      
      

      #- ./custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      red_sirp:
        ipv4_address: 192.168.70.2      
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 3g
    cpuset: "0"

  sirpElasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch2
    environment:
      - node.name=elasticsearch2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch,elasticsearch3
      - cluster.initial_master_nodes=elasticsearch,elasticsearch2,elasticsearch3      
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
    volumes:
      - volElasticsearchData2:/usr/share/elasticsearch/data 
      #- $PWD/volumes/volElasticsearchData2:/usr/share/elasticsearch/data      
    
    networks:
      red_sirp:
        ipv4_address: 192.168.70.10   
    depends_on:
      - sirpElasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 3g
    cpuset: "1"

  sirpElasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch3
    environment:
      - node.name=elasticsearch3
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=elasticsearch,elasticsearch2
      - cluster.initial_master_nodes=elasticsearch,elasticsearch2,elasticsearch3      
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - bootstrap.memory_lock=true
    volumes:
      - volElasticsearchData3:/usr/share/elasticsearch/data
      #- $PWD/volumes/volElasticsearchData3:/usr/share/elasticsearch/data
    networks:
      red_sirp:
        ipv4_address: 192.168.70.11
    depends_on:
      - sirpElasticsearch
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 3g
    cpuset: "2"



  sirpLogstash:
    image: docker.elastic.co/logstash/logstash:7.15.2
    container_name: logstash
    ports:
      - "5044:5044"
    volumes:
      - $PWD/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      #- volLogstashPipeline:/usr/share/logstash/pipeline
      #- $PWD/logstash/test.yml:/etc/logstash/conf.d/logstash.conf:ro
    networks:
      red_sirp:
        ipv4_address: 192.168.70.3
    depends_on:
      - sirpElasticsearch
      - sirpElasticsearch2
      - sirpElasticsearch3
    mem_limit: 1g


  sirpKibana:
    image: docker.elastic.co/kibana/kibana:7.15.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment: 
      ELASTICSEARCH_HOSTS: '["http://sirpElasticsearch:9200","http://sirpElasticsearch2:9200","http://sirpElasticsearch3:9200"]'
      #- ELASTICSEARCH_HOSTS=["http://sirpElasticsearch:9200","http://sirpElasticsearch2:9200","http://sirpElasticsearch3:9200"]
      # elasticsearch.ssl.verificationMode: none  
      # xpack.monitoring.ui.container.elasticsearch.enabled: "true" 
      # LOGGING_VERBOSE: "true"
     
      #ELASTICSEARCH_USERNAME: "elastic"
      #ELASTICSEARCH_PASSWORD: '123456'
      #ELASTICSEARCH_HOSTS: http://sirpElasticsearch3:9200
    volumes:
      - volkibana:/usr/share/kibana/data
      #- $PWD/volumes/volkibana:/usr/share/kibana/data
      #- $PWD/kibana/config:/usr/share/kibana/config
    networks:
      red_sirp:
        ipv4_address: 192.168.70.4
    # healthcheck:
    #   interval: 10s
    #   retries: 20
    depends_on:
      - sirpElasticsearch
      - sirpElasticsearch2
      - sirpElasticsearch3
    mem_limit: 1g
    cpuset: "3"
    # links:
    #   - sirpElasticsearch

  elastalert:
    #image: ivankrizsan/elastalert:latest
    image: jertel/elastalert2:2.2.3
    container_name: elastalert
    # cap_add:
    #   - SYS_TIME
    #   - SYS_NICE
 
    volumes:
      - ./elastAlert/config/config.yaml:/opt/elastalert/config.yaml
      - ./elastAlert/logs:/opt/logs
      - ./elastAlert/rules:/opt/rules
      #- ./elastAlert/config:/opt/config
    # links:
    #   - elasticsearch:sirpElasticsearch
    environment:
      - ES_HOST=192.168.70.2
      - ES_PORT=9200
      - ES_HOSTS=192.168.70.10,192.168.70.11

      #- ELASTICSEARCH_HOST=http://192.168.70.2
      #- ELASTICSEARCH_PORT=9200
      #- SET_CONTAINER_TIMEZONE=true
      #- ELASTALERT_INDEX=elastalert_status
      #- ELASTICSEARCH_USER=elastic
      #- ELASTICSEARCH_PASSWORD=changeme      
      #- CONTAINER_TIMEZONE=Asia/Taipei
    depends_on:
      - sirpElasticsearch
      - sirpElasticsearch2
      - sirpElasticsearch3
      - sirpKibana
    mem_limit: 1g
    cpuset: "5"
    networks:
      red_sirp:
        ipv4_address: 192.168.70.5
  

  cortex:
    #image: thehiveproject/cortex:latest
    image: thehiveproject/cortex:3.1.3
    container_name: cortex
    ports:
      - "0.0.0.0:9001:9001"
    #environment:
    #   - es_uri=http://sirpElasticsearch:9200
      #- http_proxy=${http_proxy}
      #- https_proxy=${https_proxy}  
    volumes:
      - ./cortex/application.conf:/etc/cortex/application.conf
      - ./cortex/Cortex-Analyzers/analyzers/:/opt/Cortex-Analyzers/analyzers/
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
     
    # command:
    #   --analyzer-url /opt/Cortex-Analyzers/analyzers/
    depends_on:
      - sirpElasticsearch
    mem_limit: 1g
    cpuset: "6"
    networks:
      red_sirp:
        ipv4_address: 192.168.70.6



  thehive:
    #image: thehiveproject/thehive:latest
    image: thehiveproject/thehive:3.5.1-1
    container_name: thehive
    depends_on:
      - sirpElasticsearch
      - cortex
    ports:
      - "0.0.0.0:9000:9000"
    volumes:
      - $PWD/theHive/application.conf:/etc/thehive/application.conf
    command: --no-config
    #   --cortex-port 9001      
    #   --es-uri http://elasticsearch:9200
    #   --cortex-key u8Sxu40326S8t/ljqPBHHlP5xa+u4qBu  
     
    mem_limit: 1g
    cpuset: "7"
    networks:
      red_sirp:
        ipv4_address: 192.168.70.7

volumes:
  volElasticsearchData:
  volElasticsearchData2:
  volElasticsearchData3:
  volkibana:

networks:
  red_sirp:
    driver: bridge
    ipam: 
      config:
        - subnet: "192.168.70.0/24"
          gateway: "192.168.70.1"
 
# volumes:
#   # volElasticsearchData:
#   # volElasticsearchData2:
#   # volElasticsearchData3:
#   volLogstashPipeline:
#   volKibana:
